[colors.bright]
black = "0x6e6a86"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "#e0def4"
text = "#524f67"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x26233a"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.selection]
background = "0x403d52"
text = "0xe0def4"

[colors.vi_mode_cursor]
cursor = "#e0def4"
text = "#524f67"

[font]
size = 14.5

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "~/.local/bin/tmux-sessionizer.sh \u000D"
key = "f"
mods = "Control"

[terminal.shell]
program = "/Users/oliver.bohne/.cargo/bin/nu"
# program = "/usr/local/bin/devbox"
# args = ["shell"]

[window]
decorations = "transparent"
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 20
y = 20

[env]
term = "xterm-256color"

[terminal]
